### PR TITLE
Rc<T> cleanup and currently built crates tracking

### LINKED ISSUE #1: Remove pgrep dependency

### PR DESCRIPTION
**Pull request by iscgar**
- track currently built crates using the --message-format=json argument
  to cargo (doesn't work for install, unfortunately), thereby getting
  rid of the pgrep dependency
- refactor the code to separate the logic between dependency tracking,
  drawing, and event handling
- remove Rc<T> from the code and properly describe objects lifetime
- cleanup the drawing logic to start drawing as soon as information
  is available instead of waiting for the full graph to be built in
  memory by using a DrawingPlan iterator
- print cargo output that isn't part of the build plan

closes #1, #2, #4, and #5

### CODE REVIEW

**Comment by omertuc** [comment]
Trying to find traces of the original code in there

image

Is this collapsed look on purpose?

**Comment by iscgar** [comment]
Sorry, this is indeed a major refactoring, but the logic of the original code is still there, just reorganised.

As for the collapsed view, it looked dense to me too, but I didn't have an option to run the original version on Windows, so I chalked it up to my failing memory and assumed that it was always like that. Since the original logic is intact, the only explanation that I can come up with is that I missed something, and that certain angles get cut off, for some reason.

**Comment by iscgar** [comment]
OK, found the bug. I added a commit on top with the fix.

**Comment by omertuc** [comment]
Another regression - development crates are stuck as colorful:
image

**Comment by iscgar** [comment]
Dev dependencies aren't built when executing `cargo build` since they are only used for tests and benchmarks. I accidentally removed the `-e=no-dev` argument from the `cargo tree` call, so that's why they started showing up. All fixed now.

**Pull request merged**
